//
// Created by Miles Youngblood on 12/3/2023.
//

#include "DragonPulse.h"

DragonPulse::DragonPulse() : Move(10) {}

std::string DragonPulse::getName() const {
    return "Dragon Pulse";
}

std::string DragonPulse::getDescription() const {
    return "The target is attacked with a shock wave generated by the user’s gaping mouth.";
}

int DragonPulse::getPower(const Pokemon & /*attacker*/, const Pokemon & /*defender*/) const {
    return 90;
}

Type DragonPulse::getType() const {
    return Type::DRAGON;
}

Move::Category DragonPulse::getCategory() const {
    return Category::SPECIAL;
}

namespace {
    [[maybe_unused]] std::jthread init([] -> void {
        const std::scoped_lock scopedLock(moveMutex);
        moveMap["Dragon Pulse"] = [] -> std::unique_ptr<Move> { return std::make_unique<DragonPulse>(); };
    });
}
