//
// Created by Miles on 10/2/2023.
//

#pragma once

#include "../Pokemon.h"

struct Data {
    const std::string name;
    const Type type1;
    const Type type2;
    const int baseHp;
    const int baseAttack;
    const int baseDefense;
    const int baseSpAttack;
    const int baseSpDefense;
    const int baseSpeed;
    const int baseLevel;
    const int catchRate;
};

inline std::unordered_map<Pokemon::Id, Data> pokemonLookupTable;

#include "Victini.h"
#include "Snivy.h"
#include "Servine.h"
#include "Serperior.h"
#include "Tepig.h"
#include "Pignite.h"
#include "Emboar.h"
#include "Oshawott.h"
#include "Dewott.h"
#include "Samurott.h"
#include "Patrat.h"
#include "Watchog.h"
#include "Lillipup.h"
#include "Herdier.h"
#include "Stoutland.h"
#include "Purrloin.h"
#include "Liepard.h"
#include "Pansage.h"
#include "Simisage.h"
#include "Pansear.h"
#include "Simisear.h"
#include "Panpour.h"
#include "Simipour.h"
#include "Munna.h"
#include "Musharna.h"
#include "Pidove.h"
#include "Tranquill.h"
#include "Unfezant.h"
#include "Blitzle.h"
#include "Zebstrika.h"
#include "Roggenrola.h"
#include "Boldore.h"
#include "Gigalith.h"
#include "Woobat.h"
#include "Swoobat.h"
#include "Drilbur.h"
#include "Excadrill.h"
#include "Audino.h"
#include "Timburr.h"
#include "Gurdurr.h"
#include "Conkeldurr.h"
#include "Tympole.h"
#include "Palpitoad.h"
#include "Seismitoad.h"
#include "Throh.h"
#include "Sawk.h"
#include "Sewaddle.h"
#include "Swadloon.h"
#include "Leavanny.h"
#include "Venipede.h"
#include "Whirlipede.h"
#include "Scolipede.h"
#include "Cottonee.h"
#include "Whimsicott.h"
#include "Petilil.h"
#include "Lilligant.h"
#include "Basculin.h"
#include "Sandile.h"
#include "Krokorok.h"
#include "Krookodile.h"
#include "Darumaka.h"
#include "Darmanitan.h"
#include "Maractus.h"
#include "Dwebble.h"
#include "Crustle.h"
#include "Scraggy.h"
#include "Scrafty.h"
#include "Sigilyph.h"
#include "Yamask.h"
#include "Cofagrigus.h"
#include "Tirtouga.h"
#include "Carracosta.h"
#include "Archen.h"
#include "Archeops.h"
#include "Trubbish.h"
#include "Garbodor.h"
#include "Zorua.h"
#include "Zoroark.h"
#include "Minccino.h"
#include "Cinccino.h"
#include "Gothita.h"
#include "Gothorita.h"
#include "Gothitelle.h"
#include "Solosis.h"
#include "Duosion.h"
#include "Reuniclus.h"
#include "Ducklett.h"
#include "Swanna.h"
#include "Vanillite.h"
#include "Vanillish.h"
#include "Vanilluxe.h"
#include "Deerling.h"
#include "Sawsbuck.h"
#include "Emolga.h"
#include "Karrablast.h"
#include "Escavalier.h"
#include "Foongus.h"
#include "Amoonguss.h"
#include "Frillish.h"
#include "Jellicent.h"
#include "Alomomola.h"
#include "Joltik.h"
#include "Galvantula.h"
#include "Ferroseed.h"
#include "Ferrothorn.h"
#include "Klink.h"
#include "Klang.h"
#include "Klinklang.h"
#include "Tynamo.h"
#include "Eelektrik.h"
#include "Eelektross.h"
#include "Elgyem.h"
#include "Beheeyem.h"
#include "Litwick/Litwick.h"
#include "Lampent/Lampent.h"
#include "Chandelure/Chandelure.h"
#include "Axew/Axew.h"
#include "Fraxure/Fraxure.h"
#include "Haxorus/Haxorus.h"
#include "Cubchoo/Cubchoo.h"
#include "Beartic/Beartic.h"
#include "Cryogonal/Cryogonal.h"
#include "Shelmet/Shelmet.h"
#include "Accelgor/Accelgor.h"
#include "Stunfisk/Stunfisk.h"
#include "Mienfoo/Mienfoo.h"
#include "Mienshao/Mienshao.h"
#include "Druddigon/Druddigon.h"
#include "Golett/Golett.h"
#include "Golurk/Golurk.h"
#include "Pawniard/Pawniard.h"
#include "Bisharp/Bisharp.h"
#include "Bouffalant/Bouffalant.h"
#include "Rufflet/Rufflet.h"
#include "Braviary/Braviary.h"
#include "Vullaby/Vullaby.h"
#include "Mandibuzz/Mandibuzz.h"
#include "Heatmor/Heatmor.h"
#include "Durant/Durant.h"
#include "Deino/Deino.h"
#include "Zweilous/Zweilous.h"
#include "Hydreigon/Hydreigon.h"
#include "Larvesta/Larvesta.h"
#include "Volcarona/Volcarona.h"
#include "Cobalion/Cobalion.h"
#include "Terrakion/Terrakion.h"
#include "Virizion/Virizion.h"
#include "Tornadus/Tornadus.h"
#include "Thundurus/Thundurus.h"
#include "Reshiram/Reshiram.h"
#include "Zekrom/Zekrom.h"
#include "Landorus/Landorus.h"
#include "Kyurem/Kyurem.h"
#include "Keldeo/Keldeo.h"
#include "Meloetta/Meloetta.h"
#include "Genesect/Genesect.h"
